server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for the form-service
        - id: form-service-route
          uri: lb://form-service
          predicates:
            - Path=/api/forms/**
          filters:
            - RewritePath=/api/forms(?<segment>/?.*), /api/v1/forms${segment}
        
        # ADD THIS ROUTE for the user-response-service
        - id: user-response-service-route
          uri: lb://user-response-service
          predicates:
            - Path=/api/responses/**
          filters:
            - RewritePath=/api/responses(?<segment>/?.*), /api/v1/responses${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/